eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true