spring:
  cloud:
    config:
      allow-override: true
      override-none: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: false
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true

internal:
  token: ${INTERNAL_TOKEN:dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==}
  service:
    token: ${SERVICE_TOKEN:dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==}
