spring:
  cloud:
    config:
      allow-override: true
      override-none: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: false
  instance:
    hostname: ${EUREKA_HOSTNAME}
    prefer-ip-address: true

internal:
  token: ${INTERNAL_TOKEN}
  service:
    token: ${SERVICE_TOKEN}
