spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/oauth2/**,/callback/**,/auth/**,/demo/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**,/roles/**
            - id: user-service-openapi
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api-docs/user-service
              filters:
                - RewritePath=/api-docs/user-service, /api-docs
            - id: auth-service-openapi
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api-docs/auth-service
              filters:
                - RewritePath=/api-docs/auth-service, /api-docs
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - ${CORS_ALLOWED_ORIGINS}
                allowed-methods:
                  - "GET"
                  - "POST"
                  - "PUT"
                  - "DELETE"
                  - "OPTIONS"
                  - "HEAD"
                  - "PATCH"
                allowed-headers: "*"
                allow-credentials: true

springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    persist-authorization: true
    urls:
      - name: user-service
        url: /api-docs/user-service
      - name: auth-service
        url: /api-docs/auth-service
    disable-swagger-default-url: true
    use-root-path: true
  override-with-generic-response: true



server:
  port: 8222

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

