spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/oauth2/**,/callback/**,/auth/**,/demo/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**,/roles/**

server:
  port: 8222

