spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/oauth2/**,/callback/**,/auth/**,/demo/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**,/roles/**
            - id: user-service-openapi
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api-docs/user-service
              filters:
                - RewritePath=/api-docs/user-service, /api-docs

server:
  port: 8222

jwt:
  secret:
    key: 1x8NbZAgBr91EIKrWcnvLVyTSEOnV6g4efmMp+dIS2k=

