spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/user_service
#    username: tolox
#    password: toloxpass
    jpa:
      hibernate:
        ddl-auto: none
      database: user_service
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      baseline-on-migrate: true

server:
  port: 8092