spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_SERVICE_DATASOURCE_URL}
    username: ${USER_SERVICE_DATASOURCE_USERNAME}
    password: ${USER_SERVICE_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database: ${USER_SERVICE_DATASOURCE_JPA_DATABASE}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true

server:
  port: 8092