services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_USER: tolox
      POSTGRES_PASSWORD: toloxpass
      POSTGRES_DB: user_service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 12345:5432
    networks:
      - tolo-x-db-postgres
    restart: unless-stopped

networks:
  tolo-x-internal:
  tolo-x-public:
  tolo-x-db-postgres:

volumes:
  db-postgres: