services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_USER: tolox
      POSTGRES_PASSWORD: toloxpass
      POSTGRES_DB: user_service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 12345:5432
    networks:
      - tolo-x-db-postgres
    restart: unless-stopped

  notification-preference-db:
    container_name: notification-preference-db
    image: postgres
    environment:
      POSTGRES_USER: preference_user
      POSTGRES_PASSWORD: preference_pass
      POSTGRES_DB: preference_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - notification-preference-db:/var/lib/postgresql/data
    ports:
      - 12346:5432
    networks:
      - tolo-x-db-postgres
    restart: unless-stopped

  template-db:
    container_name: template-db
    image: postgres
    environment:
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: template_pass
      POSTGRES_DB: template_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - template-db:/var/lib/postgresql/data
    ports:
      - 12347:5432
    networks:
      - tolo-x-db-postgres
    restart: unless-stopped


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    networks:
      - tolo-x-internal
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "CONTROLLER://KAFKA:9093,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  redis:
    image: redis:7.2
    container_name: redis
    networks:
      - tolo-x-internal
    ports:
      - "26379:6379"
    command: ["redis-server", "--appendonly", "no"]

networks:
  tolo-x-internal:
  tolo-x-public:
  tolo-x-db-postgres:

volumes:
  db-postgres:
  notification-preference-db:
  template-db: