services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_USER: tolox
      POSTGRES_PASSWORD: toloxpass
      POSTGRES_DB: user_service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 12345:5432
    networks:
      - tolo-x-db-postgres
    restart: unless-stopped

  config-server:
    build:
      context: ./services/config-server
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      EUREKA_HOSTNAME: discovery-service
      EUREKA_URL: http://discovery-service:8761/eureka/

    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 5s
      retries: 5
    networks:
      - tolo-x-internal

  discovery-service:
    build:
      context: ./services/discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service
      EUREKA_URL: http://discovery-service:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8761/actuator/health" ]
      interval: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - tolo-x-internal

  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - 8092:8092
    environment:
      SPRING_PROFILES_ACTIVE: native
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service
      EUREKA_URL: http://discovery-service:8761/eureka/
      USER_SERVICE_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/user_service
      USER_SERVICE_DATASOURCE_USERNAME: tolox
      USER_SERVICE_DATASOURCE_PASSWORD: toloxpass
      USER_SERVICE_DATASOURCE_JPA_DATABASE: user_service
      INTERNAL_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
      SERVICE_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
    depends_on:
      db-postgres:
        condition: service_started
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user-service:8092/actuator/health" ]
      interval: 5s
      retries: 5
    networks:
      - tolo-x-db-postgres
      - tolo-x-internal

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service
      EUREKA_URL: http://discovery-service:8761/eureka/
      SPRING_PROFILES_ACTIVE: native
      INTERNAL_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
      SERVICE_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
      GOOGLE_OAUTH2_CLIENT_ID: 494094989721-c40huttg8kd92b7gaov7o1pcerhqagfq.apps.googleusercontent.com
      GOOGLE_OAUTH2_CLIENT_SECRET: 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
      OAUTH2_CALLBACK_REDIRECT_URL: "http://localhost:8222/oauth2/callback/{registrationId}"
      JWT_SECRET_KEY: 1x8NbZAgBr91EIKrWcnvLVyTSEOnV6g4efmMp+dIS2k=
      JWT_ACCESS_EXPIRATION: 900000
      JWT_REFRESH_EXPIRATION: 604800000
      TOKEN_SECRET: 1x8NbZAgBr91EIKrWcnvLVyTSEOnV6g4efmMp+dIS2k=
      TOKEN_EXPIRATION_MSEC: 900000
      AUTHORIZED_OAUTH2_REDIRECT_URIS: http://localhost:5173/oauth2/redirect
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth-service:8091/actuator/health" ]
      interval: 5s
      retries: 5
    networks:
      - tolo-x-internal

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - 1222:8222
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service
      EUREKA_URL: http://discovery-service:8761/eureka/
      SPRING_PROFILES_ACTIVE: native
      INTERNAL_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
      SERVICE_TOKEN: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
      JWT_SECRET_KEY: 1x8NbZAgBr91EIKrWcnvLVyTSEOnV6g4efmMp+dIS2k=
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway:8222/actuator/health" ]
      interval: 5s
      retries: 5
    networks:
      - tolo-x-internal

networks:
  tolo-x-internal:
  tolo-x-public:
  tolo-x-db-postgres:

volumes:
  db-postgres: