### Template Service API Test Suite

@rootUrl = http://localhost:8094/notification-template
@templateBase = {{rootUrl}}/template
@assetBase = {{rootUrl}}/assets

### 1. Create a logical Template
POST {{templateBase}}
Content-Type: application/json

{
  "applicationCode": "TOLO_PARK",
  "templateCode": "BOOKING_CONFIRMED",
  "description": "Sent when a user successfully completes a parking booking"
}

> {% client.global.set("templateId", response.body.id); %}

### 2. Get All Templates
GET {{templateBase}}
Accept: application/json

### 3. Get Specific Template
GET {{templateBase}}/{{templateId}}
Accept: application/json

### 4. Create Version 1 (Draft)
POST {{templateBase}}/{{templateId}}/versions/1
Content-Type: application/json

{
  "channel": "EMAIL",
  "locale": "en",
  "subject": "Booking Confirmed: [[${bookingRef}]]",
  "body": "Hi [[${userName}]], your booking at [[${location}]] is confirmed for [[${time}]].",
  "engine": "THYMELEAF"
}

### 5. Publish Version 1
PATCH {{templateBase}}/{{templateId}}/publish/1
Content-Type: application/json

### 6. Render EMAIL (Active Version)
POST {{templateBase}}/render
Content-Type: application/json

{
  "applicationCode": "TOLO_PARK",
  "templateCode": "BOOKING_CONFIRMED",
  "channel": "EMAIL",
  "locale": "en",
  "data": {
    "userName": "Mindahun",
    "bookingRef": "ABC-123",
    "location": "Addis Ababa",
    "time": "12:00 PM"
  }
}

### 7. Create Security Alert Template
POST {{templateBase}}
Content-Type: application/json

{
  "applicationCode": "TOLO_AUTH",
  "templateCode": "SECURITY_ALERT_V2",
  "description": "Critical security alert for new logins"
}

> {% client.global.set("alertTemplateId", response.body.id); %}

### 8. Create Email Version 1 (DRAFT)
POST {{templateBase}}/{{alertTemplateId}}/versions/3
Content-Type: application/json

{
  "channel": "EMAIL",
  "locale": "en",
  "subject": "Security Alert: New Login Detected",
  "body": "Hi [[${userName}]], login from [[${location}]]. Use [[${assets.COMPANY_LOGO}]]",
  "engine": "THYMELEAF",
  "status": "DRAFT"
}

### 9. Get variables (Filters out assets.*)
GET {{templateBase}}/{{alertTemplateId}}/versions/3/variables
Content-Type: application/json

### 10. Preview Version 1 (DRAFT)
POST {{templateBase}}/{{alertTemplateId}}/versions/3/preview
Content-Type: application/json

{
  "channel": "EMAIL",
  "locale": "en",
  "data": {
    "userName": "Mindahun",
    "location": "Addis Ababa"
  }
}

### 11. List Global Assets
GET {{assetBase}}
Content-Type: application/json

### 12. Create a new Asset
POST {{assetBase}}
Content-Type: application/json

{
  "assetKey": "BANNER_PROMO",
  "assetUrl": "https://tolo-x.com/promo.png",
  "description": "Global promo banner"
}

### 13. Update an Asset (DANGER: Copy actual ID from Request 11)
PUT {{assetBase}}/a4734aba-d22f-4e6f-8efd-95c69dcbcfb0
Content-Type: application/json

{
  "assetKey": "COMPANY_LOGO",
  "assetUrl": "https://tolo-x.com/brand/new-logo-v3.png",
  "description": "Updated brand logo"
}