apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-user-service-db
  labels:
    app: core-user-service-db
spec:
  serviceName: core-user-service-db
  replicas: 1
  selector:
    matchLabels:
      app: core-user-service-db
  template:
    metadata:
      labels:
        app: core-user-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "tolox"
            - name: POSTGRES_PASSWORD
              value: "toloxpass"
            - name: POSTGRES_DB
              value: "user_service"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: core-user-service-db
  labels:
    app: core-user-service-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: core-user-service-db


