apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: mindaxps/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: native
            - name: USER_SERVICE_DATASOURCE_URL
              value: jdbc:postgresql://core-user-service-db:5432/user_service
            - name: USER_SERVICE_DATASOURCE_USERNAME
              value: "tolox"
            - name: USER_SERVICE_DATASOURCE_PASSWORD
              value: "toloxpass"
            - name: USER_SERVICE_DATASOURCE_JPA_DATABASE
              value: "POSTGRESQL"
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_HOSTNAME
              value: user-service
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka/
            - name: INTERNAL_TOKEN
              value: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
            - name: SERVICE_TOKEN
              value: dG9sb3hpbnRlcm5hbHNlY3JldHRva2VuZm9ybWljcm9zZXJ2aWNlcw==
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user-service
  ports:
    - port: 8092
      targetPort: 8092
