@auth_token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiQURNSU4ifV0sInN1YiI6ImpvaG5kb2UxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTc3MDE5NDg4NSwiZXhwIjoxNzcwMTk1Nzg1fQ.WLvE-L3rOugfMLWe8onunQmk9RqIPtpJHdEbAevHLR0

###
POST http://localhost:1222/auth/register
Content-Type: application/json

{
  "email": "johndoe1234@gmail.com",
  "name": "john doe",
  "password": "johndoe1234"
}

###
POST http://localhost:1222/auth/login
Content-Type: application/json

{
  "email": "johndoe1234@gmail.com",
  "password": "johndoe1234"
}

###
GET http://localhost:1222/auth/check
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:1222/auth/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}`

###
GET http://localhost:1222/users/email/johndoe1234@gmail.com
Content-Type: application/json


###
GET http://localhost:1222/demo/user/mindahunxps@gmail.com
Content-Type: application/json

###
GET http://localhost:1222/demo/user/mindahunxps@gmail.com
Content-Type: application/json


###
GET http://localhost:1222/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:1222/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}