@auth_token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJzdWIiOiJqb2huZG9lMTIzQGdtYWlsLmNvbSIsImlhdCI6MTc2MzA1MjY5MiwiZXhwIjoxNzYzMDUzNTkyfQ.Yw0jUMM9Z95chczuXrWIwcdkeoDAwzw2-YPSjdxTWSw

###
POST http://localhost:8222/auth/register
Content-Type: application/json

{
  "email": "johndoe123@gmail.com",
  "name": "john doe",
  "password": "johndoe123"
}

###
POST http://localhost:8222/auth/login
Content-Type: application/json

{
  "email": "johndoe123@gmail.com",
  "password": "johndoe123"
}

###
GET http://localhost:8222/auth/check
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8222/auth/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}`

###
GET http://localhost:8222/users/email/mindahunxps@gmail.com
Content-Type: application/json


###
GET http://localhost:8222/demo/user/mindahunxps@gmail.com
Content-Type: application/json


###
GET http://localhost:8222/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}