@auth_token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwic3ViIjoiam9obmRvZTEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NjMyMDQ0NjIsImV4cCI6MTc2MzIwNTM2Mn0.c2fmRQskY-Hbl94A3ngXmJzEHoNh4MSI0yhwtl2qvT4

###
POST http://localhost:8222/auth/register
Content-Type: application/json

{
  "email": "johndoe1234@gmail.com",
  "name": "john doe",
  "password": "johndoe1234"
}

###
POST http://localhost:8222/auth/login
Content-Type: application/json

{
  "email": "johndoe123@gmail.com",
  "password": "johndoe123"
}

###
GET http://localhost:8222/auth/check
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8222/auth/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}`

###
GET http://localhost:8222/users/email/mindahunxps@gmail.com
Content-Type: application/json


###
GET http://localhost:8222/demo/user/mindahunxps@gmail.com
Content-Type: application/json


###
GET http://localhost:8222/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8222/users/me
Content-Type: application/json
Authorization: Bearer {{auth_token}}